//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lucas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lucas.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string CMD_CLEAR_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_CLEAR_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the screen.
        /// </summary>
        internal static string CMD_CLEAR_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_CLEAR_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        internal static string CMD_CLEAR_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_CLEAR_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count circle ellipse.
        /// </summary>
        internal static string CMD_COUNT_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_COUNT_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the number of existing shape elements. If one or more shape types are specifies as arguments the result will be filtered. If no argument is specified all it will be the total of all..
        /// </summary>
        internal static string CMD_COUNT_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_COUNT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count [shape1, ... shapeN].
        /// </summary>
        internal static string CMD_COUNT_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_COUNT_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete 5.
        /// </summary>
        internal static string CMD_DELETE_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_DELETE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; deleted shape: {0} {1}.
        /// </summary>
        internal static string CMD_DELETE_SUCCESS {
            get {
                return ResourceManager.GetString("CMD_DELETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes a shape given a key..
        /// </summary>
        internal static string CMD_DELETE_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_DELETE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        internal static string CMD_DELETE_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_DELETE_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw auto.
        /// </summary>
        internal static string CMD_DRAW_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_DRAW_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws a givven shape (by key) on the the existing WPF window. If the word auto is specified instead of the shape key, everytime a shape is listed it will get automatically drawn in at the target. It will also print the definition of the shape in the console with a friendly format. .
        /// </summary>
        internal static string CMD_DRAW_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_DRAW_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draw auto | draw [shape1, ... shapeN].
        /// </summary>
        internal static string CMD_DRAW_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_DRAW_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string CMD_EXIT_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_EXIT_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit and close the application.
        /// </summary>
        internal static string CMD_EXIT_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_EXIT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        internal static string CMD_EXIT_SYNTAXIS {
            get {
                return ResourceManager.GetString("CMD_EXIT_SYNTAXIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help draw circle.
        /// </summary>
        internal static string CMD_HELP_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_HELP_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists one or more shape and command definitions. If no argument is specifies it will list all commands and shapes definitions in that order..
        /// </summary>
        internal static string CMD_HELP_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_HELP_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help [shape1, ... shapeN].
        /// </summary>
        internal static string CMD_HELP_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_HELP_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list circle ellipse.
        /// </summary>
        internal static string CMD_LIST_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_LIST_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List a set of shapes. If one or more shape types are specifies as arguments the result will be filtered. If no argument is specified all existing shapes will be enumerated..
        /// </summary>
        internal static string CMD_LIST_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_LIST_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list [shape1, ... shapeN].
        /// </summary>
        internal static string CMD_LIST_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_LIST_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load filename1 [filename2, ... filenameN].
        /// </summary>
        internal static string CMD_LOAD_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_LOAD_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads shape definitions from one or multiple files at once..
        /// </summary>
        internal static string CMD_LOAD_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_LOAD_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load.
        /// </summary>
        internal static string CMD_LOAD_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_LOAD_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over 4.
        /// </summary>
        internal static string CMD_OVER_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_OVER_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given a shape key, this command lists all the shapes that overlaps the given shape..
        /// </summary>
        internal static string CMD_OVER_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_OVER_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over shape_element_key.
        /// </summary>
        internal static string CMD_OVER_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_OVER_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save lucas.txt.
        /// </summary>
        internal static string CMD_SAVE_EXAMPLE {
            get {
                return ResourceManager.GetString("CMD_SAVE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves shape definitions to file..
        /// </summary>
        internal static string CMD_SAVE_SUMMARY {
            get {
                return ResourceManager.GetString("CMD_SAVE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save filename.
        /// </summary>
        internal static string CMD_SAVE_SYNTAX {
            get {
                return ResourceManager.GetString("CMD_SAVE_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires {1} argument values and we got {2}..
        /// </summary>
        internal static string ERROR_ARGUMENT_COUNT {
            get {
                return ResourceManager.GetString("ERROR_ARGUMENT_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse to {0} token \&quot;{1}\&quot; at position {2}..
        /// </summary>
        internal static string ERROR_ARGUMENT_TYPE {
            get {
                return ResourceManager.GetString("ERROR_ARGUMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t write messages to queue \&quot;{0}\&quot;..
        /// </summary>
        internal static string ERROR_CANT_WRITE_TO_QUEUE {
            get {
                return ResourceManager.GetString("ERROR_CANT_WRITE_TO_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; was not found..
        /// </summary>
        internal static string ERROR_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Error: .
        /// </summary>
        internal static string ERROR_PRINT {
            get {
                return ResourceManager.GetString("ERROR_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape with key {0} was not found..
        /// </summary>
        internal static string ERROR_SHAPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_SHAPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request doesn&apos;t seem valid..
        /// </summary>
        internal static string ERROR_UNKNOW_REQUEST {
            get {
                return ResourceManager.GetString("ERROR_UNKNOW_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; {0}:\n\tSyntax: {1}:\n\tSummary: {2}\n\tExample: {3}.
        /// </summary>
        internal static string HELP_CMD_DEFINITION_FORMAT {
            get {
                return ResourceManager.GetString("HELP_CMD_DEFINITION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; {0}:\n\tSummary: {1}\n\tExample: {2}.
        /// </summary>
        internal static string HELP_SHAPE_DEFINITION_FORMAT {
            get {
                return ResourceManager.GetString("HELP_SHAPE_DEFINITION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Listing Shapes containin point at {0} {1}....
        /// </summary>
        internal static string LISTING_SHAPES_CONTAINING_POINT {
            get {
                return ResourceManager.GetString("LISTING_SHAPES_CONTAINING_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Listing Shapes overlaping {0} {1}....
        /// </summary>
        internal static string LISTING_SHAPES_OVERLAPING_SHAPE {
            get {
                return ResourceManager.GetString("LISTING_SHAPES_OVERLAPING_SHAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; .
        /// </summary>
        internal static string PROMPT {
            get {
                return ResourceManager.GetString("PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; already exists. Do you want to overwrite it (y/n)?.
        /// </summary>
        internal static string PROMPT_FILE_OVERWRITE {
            get {
                return ResourceManager.GetString("PROMPT_FILE_OVERWRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circle 1.7 -5.05 6.9.
        /// </summary>
        internal static string SHAPE_CIRCLE_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_CIRCLE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circle with centre at ({0}, {1}) and radius {2}.
        /// </summary>
        internal static string SHAPE_CIRCLE_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_CIRCLE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cirlce shape..
        /// </summary>
        internal static string SHAPE_CIRCLE_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_CIRCLE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; Count: {0}.
        /// </summary>
        internal static string SHAPE_COUNT_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_COUNT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donut 4.5 7.8 1.5 1.8.
        /// </summary>
        internal static string SHAPE_DONUT_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_DONUT_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to donut with centre at ({0}, {1}), internal radius {2} and external radius {3}.
        /// </summary>
        internal static string SHAPE_DONUT_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_DONUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donut shape. Delimited by two concentric circles..
        /// </summary>
        internal static string SHAPE_DONUT_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_DONUT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ellipse 1.7 -5.05 6.9 4.6.
        /// </summary>
        internal static string SHAPE_ELLIPSE_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_ELLIPSE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ellipse with centre at ({0}, {1}), width {2} and height {3}.
        /// </summary>
        internal static string SHAPE_ELLIPSE_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_ELLIPSE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse shape..
        /// </summary>
        internal static string SHAPE_ELLIPSE_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_ELLIPSE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polygon 34 32 45 32 34 65 43 56.
        /// </summary>
        internal static string SHAPE_POLYGON_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_POLYGON_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polygon with vertexes {0}.
        /// </summary>
        internal static string SHAPE_POLYGON_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_POLYGON_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A poligon. The number of sides is 3 or more..
        /// </summary>
        internal static string SHAPE_POLYGON_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_POLYGON_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt; shape {0}: .
        /// </summary>
        internal static string SHAPE_PRINT {
            get {
                return ResourceManager.GetString("SHAPE_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rectangle 3.5 2.0 5.6 7.2.
        /// </summary>
        internal static string SHAPE_RECTANGLE_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_RECTANGLE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rectangle with top left cornet at ({0}, {1}), height {2} and width {3}.
        /// </summary>
        internal static string SHAPE_RECTANGLE_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_RECTANGLE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle shape. Four sides, all internal angles measure 90 degrees..
        /// </summary>
        internal static string SHAPE_RECTANGLE_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_RECTANGLE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square 3.55 4.1 2.77.
        /// </summary>
        internal static string SHAPE_SQUARE_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_SQUARE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to square with top left corner at ({0}, {1}) and length {2}.
        /// </summary>
        internal static string SHAPE_SQUARE_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_SQUARE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square shape. Four sides with same length, all internal angles measure 90 degrees..
        /// </summary>
        internal static string SHAPE_SQUARE_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_SQUARE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start 100 100 50 50 20 5.
        /// </summary>
        internal static string SHAPE_STAR_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_STAR_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A star is a polygo that has at least 3 outer edges and it is constructed from the center, the first outer edge,  the radio of the internal edge, and the number of outer edges (the total internal edges is the same)..
        /// </summary>
        internal static string SHAPE_STAR_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_STAR_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triangle 4.5 1 -2.5 -33 23 0.3.
        /// </summary>
        internal static string SHAPE_TRIANGLE_EXAMPLE {
            get {
                return ResourceManager.GetString("SHAPE_TRIANGLE_EXAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triangle with vertices at ({0}, {1}), ({2}, {3}) and ({4}, {5}).
        /// </summary>
        internal static string SHAPE_TRIANGLE_FORMAT {
            get {
                return ResourceManager.GetString("SHAPE_TRIANGLE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle shape. Three sides..
        /// </summary>
        internal static string SHAPE_TRIANGLE_SUMMARY {
            get {
                return ResourceManager.GetString("SHAPE_TRIANGLE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: .
        /// </summary>
        internal static string WARNING_PRINT {
            get {
                return ResourceManager.GetString("WARNING_PRINT", resourceCulture);
            }
        }
    }
}
